/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/chriskery/hadoop-operator/pkg/apis/kubecluster.org/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HadoopJobLister helps list HadoopJobs.
// All objects returned here must be treated as read-only.
type HadoopJobLister interface {
	// List lists all HadoopJobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.HadoopJob, err error)
	// HadoopJobs returns an object that can list and get HadoopJobs.
	HadoopJobs(namespace string) HadoopJobNamespaceLister
	HadoopJobListerExpansion
}

// hadoopJobLister implements the HadoopJobLister interface.
type hadoopJobLister struct {
	indexer cache.Indexer
}

// NewHadoopJobLister returns a new HadoopJobLister.
func NewHadoopJobLister(indexer cache.Indexer) HadoopJobLister {
	return &hadoopJobLister{indexer: indexer}
}

// List lists all HadoopJobs in the indexer.
func (s *hadoopJobLister) List(selector labels.Selector) (ret []*v1alpha1.HadoopJob, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HadoopJob))
	})
	return ret, err
}

// HadoopJobs returns an object that can list and get HadoopJobs.
func (s *hadoopJobLister) HadoopJobs(namespace string) HadoopJobNamespaceLister {
	return hadoopJobNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// HadoopJobNamespaceLister helps list and get HadoopJobs.
// All objects returned here must be treated as read-only.
type HadoopJobNamespaceLister interface {
	// List lists all HadoopJobs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.HadoopJob, err error)
	// Get retrieves the HadoopJob from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.HadoopJob, error)
	HadoopJobNamespaceListerExpansion
}

// hadoopJobNamespaceLister implements the HadoopJobNamespaceLister
// interface.
type hadoopJobNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all HadoopJobs in the indexer for a given namespace.
func (s hadoopJobNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.HadoopJob, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HadoopJob))
	})
	return ret, err
}

// Get retrieves the HadoopJob from the indexer for a given namespace and name.
func (s hadoopJobNamespaceLister) Get(name string) (*v1alpha1.HadoopJob, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("hadoopjob"), name)
	}
	return obj.(*v1alpha1.HadoopJob), nil
}
