/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	kubeclusterorgv1alpha1 "github.com/chriskery/hadoop-cluster-operator/pkg/apis/kubecluster.org/v1alpha1"
	versioned "github.com/chriskery/hadoop-cluster-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/chriskery/hadoop-cluster-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/chriskery/hadoop-cluster-operator/pkg/client/listers/kubecluster.org/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HadoopClusterInformer provides access to a shared informer and lister for
// HadoopClusters.
type HadoopClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HadoopClusterLister
}

type hadoopClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHadoopClusterInformer constructs a new informer for HadoopCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHadoopClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHadoopClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHadoopClusterInformer constructs a new informer for HadoopCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHadoopClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeclusterV1alpha1().HadoopClusters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeclusterV1alpha1().HadoopClusters(namespace).Watch(context.TODO(), options)
			},
		},
		&kubeclusterorgv1alpha1.HadoopCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *hadoopClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHadoopClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hadoopClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubeclusterorgv1alpha1.HadoopCluster{}, f.defaultInformer)
}

func (f *hadoopClusterInformer) Lister() v1alpha1.HadoopClusterLister {
	return v1alpha1.NewHadoopClusterLister(f.Informer().GetIndexer())
}
